<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js.opal</string>
		<string>opal</string>
		<string>js.rb</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>Opal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.opal</string>
	<key>uuid</key>
	<string>722C39D2-3AC5-4351-88B7-66E1C25F5588</string>
</dict>
</plist>
